### ISSUE TITLE
problems displaying ram value

### ISSUE THREAD

**Issue by gatosardina** [jeticg/Evangelion-Uebersicht-Widget#1]
at times i've seen the widget display that the computer is using more than 100% of the memory (108%, 104% etc)
but if i check the actual free memory its around 800mb (i have 4 gb of ram)
also, am i going crazy or evangelion is japanese? what is the chinese supposed to mean? i'm a bit confused

**Comment by jeticg** [comment]
I'll look into the memory issues. The Chinese is the traditional timing method used by Chinese and later learned by Japanese back in Tang Dynasty, which divides the day into 12 period and represents them by Earthly Brene(地支). It is not very commonly used now, but I developed this widget for my girlfriend and this is something we want on our desktop.

**Comment by jeticg** [comment]
Also, this is only an Evangelion style widget, because I am learning German so the interface is actually in German. So yes, this is a very personalised widget. The memory problem could be resulting from the system summing functions not working properly with float values, at this point I don't really know how to fix this issue. I'll try to change the mem cell into displaying memory usage in quantity instead of percentage later.
