### ISSUE TITLE
clicking cell not working

### ISSUE THREAD

**Issue by josecarlosc** [jeticg/Evangelion-Uebersicht-Widget#10]
i'm using mac os sierra, when clicking next song or the trash icon the functions is not working

**Comment by josecarlosc** [comment]
also the warning signs shows "WARNUNG" instead of warning

**Comment by jeticg** [comment]
You need to check your Übersicht settings on interactions with the widgets. For the warning message, it's a multi language problem I think, because despite supporting English, the base interface is actually German. I'll look into the issue.

**Comment by josecarlosc** [comment]
thank you for your help, i just love this theme, where can i get the wallpaper that you are using? is there a way to get time in 12 hour format instead of 24 hours? also this is happening.
<img width="326" alt="screen shot 2016-10-27 at 6 33 52 pm" src="https://cloud.githubusercontent.com/assets/4434081/19788038/1fa33dac-9c74-11e6-8c52-12a214ec717e.png">

**Comment by jeticg** [comment]
Sorry about this, I have to admit I haven't checked the English version after the last update(as one can see, I am lazy). I'll look into this. As for the wallpaper I am using, I have attached it under this comment. As for the 12 hour format, personally I do not support it because it does not really make sense to me, but you can definitely change it by modifying the code a bit.
![neon_genesis_evangelion_nerv_1920x1200 jpg](https://cloud.githubusercontent.com/assets/7542292/19790625/705dc79a-9c6e-11e6-9581-23c52bac3715.png)

**Comment by josecarlosc** [comment]
thank you for the wall paper,i will try to fiddle with the position of the text for the empty trash can. thank you for your help.

edit: found the code, but tried to add this lines but it did not work

ampm = (hh>=12)?'pm':'am';
hh = hh%12;
hh = hh?hh:12;
hh = hh<10?'0'+hh:hh;
min = min<10?'0'+min:min;

**Comment by josecarlosc** [comment]
this is a picture of my desktop as it is right now, i changed the Warnung to warning and as you can see i changed my desktop folder icon with one of your warning figures in order to make it part of the background, the only thing is missing is the 12h format (at least for me)
<img width="1440" alt="screen shot 2016-10-27 at 11 48 29 pm" src="https://cloud.githubusercontent.com/assets/4434081/19794424/f5f8ae98-9c9f-11e6-9d0a-3387c2e63792.png">

**Comment by jeticg** [comment]
I am glad you like it. Like I said I do not provide support for 12hour format, all I can do now is to wish you good luck!
