### ISSUE TITLE
CPU load on warning.

### ISSUE THREAD

**Issue by donkahlero** [jeticg/Evangelion-Uebersicht-Widget#11]
Hi guys,
first of all: very nice widget!

Nevertheless, as soon as my battery drains down to 20%, the warnings are starting to arise on the cells. Which is - perse - no issue at all. But unfortunately, the rendering of the flashing cells is apparently heavy on the CPU. After half a minute, the fan goes nuts and the battery drains even faster.

My suggestion just color the battery tile in red - without flashing - to be better on the CPU.

I am running a MB Pro early '15 with the lowest i5 + 16GB RAM.

Cheers

**Comment by donkahlero** [comment]
+ ofc as soon as the CPU load is high, this warning will increase the load even more. Maybe you can just color the CPU tile red in that case.

**Comment by jeticg** [comment]
Hi,

Thanks for contacting me. This is a known issue, after all I have been looking for ways to improve energy consumption for this widget for quite a while, and to tell you the truth, it really is a trade off. After all, this widget’s primary purpose is to serve my demands, so when it comes to my approach, it would be very much tailored for myself.

I personally own 4 Macs, two 15’ MacBook Pros, one 11’ lowest MacBook Air, and a Mac Pro trash can. I don’t often use my computers without power supply, and even when I do, it’s like 4-5 hours tops, which is something even my lowest MBA could do(with übersicht). However, the power this widget requires is still very high, part of the reason is that the graphical interface of this widget is entirely accomplished by CSS, which means I do literally draw every lines by hand.

Now, the solution. The easiest ways are:
1. Lower the refresh frequency, right now it's once every 3000ms. You can change the value to 5000ms, I think it’s going to be a lot better.
2. Lower the battery warning level from 20% to 10% or perhaps 5%. This feature, in fact this entire widget(just like most of the other widgets) does absolutely nothing except for looking cool, it’s not like your Mac is not going to let you know when you are out of juice.

Both of these changes are relatively easy with a bit of programming background. The code is in the index.coffee file.

If you are still not satisfied with my answers, I can take a note so when I do find time to work on some improvements, I might think of something. But there is no promise sadly, I am awfully busy and as long as the widget works(for me obviously), I don’t think I could spare enough time on it. After all, it’s only a hobby.

Best wishes.

—
Jetic
jetic@me.com

**Comment by jeticg** [comment]
Oh by the way, this is what my desktop looks like.

Right in the middle is another one of my widgets that displays the status of my remote computers. Yeah, I am showing off.


—
Jetic
jetic@me.com

**Comment by jeticg** [comment]
OK, so I managed to completely resolve this problem in 0.X2a. Please do check it out.

**Comment by donkahlero** [comment]
Checked it out... Kinda the same for me. Maybe I will just fork for personal use and remove the coloring of all tiles (and the flashing) :)
