### ISSUE TITLE
[Info] Font size

### ISSUE THREAD

**Issue by hreality** [jeticg/Evangelion-Uebersicht-Widget#6]
Cell 51 Input/output attempted to change font size however OBytes doesnt change size with other info (IBYTES/OBYTES text and IBYTES number)

**Comment by jeticg** [comment]
Sorry, I don't know what you are talking about, perhaps a grammar check would be better.

**Comment by jeticg** [comment]
I assume you are talking about the font-size of the Network usage cells, in that case the text "IBYTES/S" and "OBYTES/S" are both placed under Cell 52, where the actual digits are presented in Cell 52 and Cell 55. This is due to the fact that I want to make Cell 52 and 55 visually connected without blocking the display of contents.

**Comment by hreality** [comment]
Correct and both are using div class contentS
In the css portion:
   .contentS
        transform:rotate(-90deg)
        font-style: Black
        font-size: **_15px_**  <---
        z-index:99999
Changing the value changes the size of the text in those cells except for the network value under OBYTES it stays large

**Comment by jeticg** [comment]
No. The digits are using class `content` and the `font-size`s are manually specified to be 25px.
My CSS classes doesn't always contain all the specifications, they are merely templates.

**Comment by hreality** [comment]
Ty, located.. not sure how I missed it before. Next project will be loading local IP, SSID/Network & device (en0 or en1 etc.)
